### ISSUE TITLE
StartListening Problem.

### ISSUE THREAD

**Issue by PROPPO** [Cloet/AsyncClientServer#13]
Hi, if i use this for start the server:
"string ip = "192.168.1.177";
int port = 1234;
listener.StartListening(ip, port);"
In the file "AsyncSocketListener.cs" on line 54 return this exception: System.IndexOutOfRangeException: 'index was outside the bounds of the array'

**Comment by Cloet** [comment]
You're probably using a wrong ip for your pc. For the server you can just use "127.0.0.1" and connect with your client

**Comment by Cloet** [comment]
You're probably using a wrong ip check the ip of your pc in cmd with ipconfig.

**Comment by PROPPO** [comment]
The ip is correct, this error also happens with the client if i use this code:
"
string ip = "192.168.1.177";
int port = 1234;
Client.StartClient(Ip, Port);
"
Can it be my visual studio? because two days ago it didn't give me this problem.

**Comment by Cloet** [comment]
Hmm weird I just tested it and it seems to work fine for me. Is it possible the ip of the device changed since two days ago or did you just check ?

**Comment by PROPPO** [comment]
I leave you my server project, could you check if it gives you the exception?
[Mediafire](https://www.mediafire.com/file/nm1maju5auphct0/test.rar/file)
If i use 127.0.0.1 work but if i use my ipconfig ip not work, same with the client.

**Comment by Cloet** [comment]
when I use your project with my internal ip I don't have any issues.

**Comment by PROPPO** [comment]
So is a my problem, sorry for the Issue.

**Comment by Cloet** [comment]
No problem it's a weird issue you're having

**Comment by PROPPO** [comment]
I had resolved this errore with the remove:
var host = Dns.GetHostEntry(ip);
var ipServer = host.AddressList[0];
And create:
var ipServer = Dns.GetHostAddresses(ip).FirstOrDefault();

**Comment by Cloet** [comment]
I've implemented the Dns.getHostAddresses() in the project and pushed the new updated version.

**Comment by PROPPO** [comment]
I think i found also problem with the "Dns.getHostAddresses()", now the problem is when i send more message with: a.SendMessage("TEST", false);  After 2/3 message the client return this exception:
File: AsyncClient.cs
Line: 132
Exception: Destination socket is not connected.
This error never occurred to me before the change.

**Comment by Cloet** [comment]
The client loses connection to the server, I’ll take a look when I’m home.

**Comment by PROPPO** [comment]
I have tried without Dns.getHostAddresses() using IPaddress.parse("127.0.0.1") but the problem persist.

**Comment by Cloet** [comment]
I don't think that's your issue, at some point the client disconnects from the server but I'm unable to recreate your problem.

**Comment by PROPPO** [comment]
I don't know, i have this exception in the server: System.ObjectDisposedException before the crash client.

**Comment by Cloet** [comment]
When you use .Dispose() you can’t reuse the client or server and it wont’t receice or transmit messages

**Comment by PROPPO** [comment]
Yes i know, but i don't use dispose, this is the problem.
Example:
Server have the button for send a message with this code:
Server.SendMessage(1,Textbox1.Text, false);
The client receive my message and use this code:
"
a.SendMessage("Message received.", false);
Thread Th_Test = new Thread(() =>
{
	bool Result = 1 > 0;
	a.SendMessage("result:," + Result, false);
});
Th_Test.Start();"
Now the server receive the message and return this exception: System.ObjectDisposedException
And the client return this exception: Destination socket is not connected.
